// Lista paesi specifica per il brand xcart
export const countries = [
    "Afghanistan",
    "Albania",
    "Algeria",
    "Argentina",
    "Australia",
    "Austria",
    "Azerbaijan",
    "Bahrain",
    "Belgium",
    "Bielorussia",
    "Bolivia",
    "Bonaire",
    "Brasil",
    "Brunei",
    "Bulgaria",
    "Burma",
    "Canada",
    "Chile",
    "Colombia",
    "Croatia",
    "Cyprus",
    "Czech Republic",
    "Denmark",
    "Ecuador",
    "Egypt",
    "Estonia",
    "Falkland Islands",
    "Finland",
    "France",
    "French Guyana",
    "French Polynesia",
    "Germany",
    "Greece",
    "Guyana",
    "Hungary",
    "Indonesia",
    "Iran",
    "Iraq",
    "Ireland",
    "Israel",
    "Italy",
    "Japan",
    "Jordan",
    "Kuwait",
    "Laos",
    "Latvia",
    "Lebanon",
    "Liberia",
    "Libya",
    "Lithuania",
    "Luxembourg",
    "Malaysia",
    "Malta",
    "Mexico",
    "Moldova",
    "Montenegro",
    "Netherlands",
    "Norway",
    "Oman",
    "Palestinian Territory",
    "Paraguay",
    "Peru",
    "Philippines",
    "Poland",
    "Portugal",
    "Quatar",
    "Romania",
    "Saint Eustatius and Saba",
    "Saudi Arabia",
    "Seychelles",
    "Slovakia",
    "Slovenia",
    "South Georgia",
    "Spain",
    "Suriname",
    "Sweden",
    "Swiss",
    "Syria",
    "Thailand",
    "Timor-Leste",
    "Turkey",
    "Turks and Caicos",
    "UK",
    "Ucraina",
    "United Arab Emirates",
    "United States",
    "Uruguay",
    "Venezuela",
    "Vietnam",
    "Yemen",
    "Zambia",
  ];
